site_name: HSSM
repo_name: lnccbrown/HSSM
repo_url: https://github.com/lnccbrown/HSSM/
edit_uri: edit/main/docs

nav:
  - Home:
      - Overview: index.md
      - Credits: credits.md
      - License: license.md
      - Changelog: changelog.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - Getting started: getting_started/getting_started.ipynb
  - API References:
      - hssm: api/hssm.md
      - hssm.distribution_utils: api/distribution_utils.md
      - hssm.likelihoods: api/likelihoods.md
      - hssm.defaults: api/defaults.md
  - Tutorials:
      - Main tutorial: tutorials/main_tutorial.ipynb
      - Understanding likelihood functions in HSSM: tutorials/likelihoods.ipynb
      - Using lapse probabilities: tutorials/lapse_prob_and_dist.ipynb
      - Using HSSM low-level API directly with PyMC: tutorials/pymc.ipynb
      - Using Models from Hugging Face: tutorials/hugging_face_onnx_models.ipynb
  - Contributing: CONTRIBUTING.md

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      execute: True
      execute_ignore:
        - getting_started/getting_started.ipynb
        - tutorials/main_tutorial.ipynb
        - tutorials/likelihoods.ipynb
        - .ipynb_checkpoints/*.ipynb
      allow_errors: false
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv
            - https://mkdocstrings.github.io/griffe/objects.inv
          options:
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
            docstring_style: "numpy"
            docstring_section_style: "list"
            show_root_members_full_path: true
            show_object_full_path: false
            show_category_heading: true
            show_signature_annotations: true
            show_source: false
            group_by_category: false
            signature_crossrefs: true
theme:
  logo: images/navlogo.png
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.action.view
    - content.action.edit
    - header.autohide
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  homepage: "https://lnccbrown.github.io/HSSM/"

extra_css:
  - "styles/extra.css"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
