site_name: HSSM

nav:
    - Home: index.md
    - Getting Started: notebooks/004_using_base_hssm_func.ipynb
    - HSSM Class Code Documentation: hssm.md
    - Default Configurations for HSSM Models: config.md
    - Pymc Distribution Documentation: wfpt.md
    - DDM Code Documentation: base.md
    - Using Models from Hugging Face: notebooks/hugging_face_onnx_models.ipynb
    - Contributing Guidelines: CONTRIBUTING.md

plugins:
  - search
  - mknotebooks:
      execute: True
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              options:
                  docstring_style: numpy
theme:
  name: material
  palette:
    primary: 'white'
    accent: 'blue'
  mode: 'dark'  # 'light' or 'dark'
  logo: 'images/HSSM2_Logo_Transparent600.png'


extra_css:
  - 'styles/extra.css'

