site_name: HSSM

nav:
    - Home: index.md
    - Getting Started: 004_using_base_hssm_func.ipynb
    - HSSM Class Code Documentation: hssm.md
    - Pymc Distribution Documentation: wfpt.md
    - DDM Code Documentation: base.md
    - Using Models from Hugging Face: hugging_face_onnx_models.ipynb
    - Model Configuration: config.md

plugins:
  - search
  - mknotebooks
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              options:
                  docstring_style: numpy
theme:
  name: material
