[tool.poetry]
name = "HSSM"
version = "0.1.0"
description = ""
authors = [
    "Aisulu Omar <aisulu_omar@brown.edu>",
    "Paul Xu <yang_xu@brown.edu>",
    "Alexander Fengler <alexander_fengler@brown.edu>",
    "Michael Frank <michael_frank@brown.edu>"
]
readme = "README.md"
license = "MIT"
#packages = [
#    { include = "HSSM", from = "src/hssm" }
#]
repository = "https://github.com/lnccbrown/HSSM"
keywords = ["HDDM", "HSSM", "pymc"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
scipy = "1.10.1"
pymc = "^5.0.1"
arviz = "^0.14.0"
numpy = "^1.23.4"
onnx = "^1.12.0"
jax = "^0.4.0"
jaxlib = "^0.4.0"
bambi = "^0.11.0"
formulae = "^0.4.0"
ssm-simulators = "^0.3.0"
mknotebooks = "^0.7.1"
mkdocs-material = "^9.1.15"
mkdocstrings-python = "^1.1.2"
huggingface-hub = "^0.15.1"
onnxruntime = "^1.15.0"

[tool.poetry.group.dev.dependencies]
pylint = "^2.6.0"
pytest = "^7.3.1"
black = "^22.8.0"
isort = "^5.10.1"
mypy = "^0.981"
pre-commit = "^2.20.0"
jupyterlab = "^3.4.8"
ipykernel = "^6.16.0"
hddm-wfpt = {git = "https://github.com/brown-ccv/hddm-wfpt.git"}
autoflake = "^2.0.0"
numpyro = "^0.10.1"
ipywidgets = "^8.0.3"
graphviz = "^0.20.1"
viztracer = "^0.15.6"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile="black"

[tool.pylint.basic]
good-names = "i,j,k,ex,Run,_,df,pc"

[tool.pylint.messages_control]
disable = "C0103, C0114, E0012, E0401, R0912, R0913, R0914, R0915, W0221, W0621"

[tool.pylint.format]
max-line-length = "88"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.mypy]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
