[tool.poetry]
name = "HSSM"
version = "0.1.0"
description = ""
authors = [
    "Aisulu Omar <aisulu_omar@brown.edu>",
    "Paul Xu <yang_xu@brown.edu>",
    "Alexander Fengler <alexander_fengler@brown.edu>"
]
readme = "README.md"
license = "MIT"
packages = [
    { include = "", from = "hssm" }
]
repository = "https://github.com/lnccbrown/HSSM"
keywords = ["HDDM", "HSSM", "pymc"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
pytest = "^6.2.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint.basic]
good-names = "i,j,k,ex,Run,_,df,pc"

[tool.pylint.messages_control]
disable = "C0330, C0326, R0912, R0913, R0914, R0915"

[tool.pylint.format]
max-line-length = "88"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
