[tool.poetry]
name = "HSSM"
version = "0.1.0"
description = ""
authors = [
    "Aisulu Omar <aisulu_omar@brown.edu>",
    "Paul Xu <yang_xu@brown.edu>",
    "Alexander Fengler <alexander_fengler@brown.edu>",
    "Michael Frank <michael_frank@brown.edu>"
]
readme = "README.md"
license = "MIT"
#packages = [
#    { include = "HSSM", from = "src/hssm" }
#]
repository = "https://github.com/lnccbrown/HSSM"
keywords = ["HDDM", "HSSM", "pymc"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
scipy = "1.9.1"
pymc = "^4.2.1"
aesara = "^2.8.6"
arviz = "^0.12.1"
numba = "^0.56.2"
setuptools = "^65.5.0"
numpy = "^1.23.4"
ipykernel = "^6.16.0"
ssms = {git = "https://github.com/AlexanderFengler/ssm_simulators"}

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
pytest = "^6.2.1"
black = "^22.8.0"
isort = "^5.10.1"
mypy = "^0.981"
pre-commit = "^2.20.0"
jupyterlab = "^3.4.8"
Cython = "^0.29.32"
hddm-wfpt = {git = "https://github.com/brown-ccv/hddm-wfpt.git"}

[tool.poetry.group.dev.dependencies]
hddm-wfpt = {git = "https://github.com/brown-ccv/hddm-wfpt.git"}
jupyter = "^1.0.0"


[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile="black"

[tool.pylint.basic]
good-names = "i,j,k,ex,Run,_,df,pc"

[tool.pylint.messages_control]
disable = "C0114, R0912, R0913, R0914, R0915"

[tool.pylint.format]
max-line-length = "88"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=1.2.0", "cython", "setuptools"]
build-backend = "poetry.core.masonry.api"
