site_name: HSSM

nav:
    - Home: index.md
    - HSSM Class Code Documentation: hssm.md
    - Base Code Documentation: wfpt.md
    - DDM Code Documentation: base.md
    - Basic Tutorial: 004_using_base_hssm_func.ipynb

plugins:
  - search
  - mknotebooks
  - mkdocstrings:
      default_handler: python
theme:
  name: material



