site_name: HSSM

nav:
    - Home: index.md
    - Basic Tutorial: 004_using_base_hssm_func.ipynb
    - HSSM Code Documentation: hssm.md
    - WFPT Code Documentation: wfpt.md
plugins:
  - search
  - mknotebooks
  - mkdocstrings:
      default_handler: python
theme:
  name: material



