site_name: HSSM

nav:
    - Home: index.md
    - HSSM Class Code Documentation: hssm.md
    - Pymc Distribution Documentation: wfpt.md
    - DDM Code Documentation: base.md
    - Basic Tutorial: 004_using_base_hssm_func.ipynb

plugins:
  - search
  - mknotebooks
  - mkdocstrings:
      default_handler: python
      handlers:
          python:
              options:
                  docstring_style: numpy
theme:
  name: material



