name: Run slow tests

on:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: install pymc and poetry
        run: |
          mamba info
          mamba install -c conda-forge pymc poetry

      - name: install hssm
        run: |
          poetry export --with dev --without-hashes --output=req.txt
          grep -v -E '^jax\[cuda12\]|^nvidia|^jax\-cuda12' req.txt >> requirements.txt
          pip install -r requirements.txt
          pip install -e .

      - name: Run slow tests
        run: pytest -s tests/slow
