name: Run tests

on:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: show env info
        shell: bash -el {0}
        run: |
          mamba info

      - name: install pymc
        run: mamba install -c conda-forge pymc=5.10

      - name: install hssm
        run: pip install -e .

      - name: Run mypy
        run: mypy src

      - name: Check styling
        run: black . --check

      - name: Linting
        run: ruff check .

      - name: Run tests
        run: pytest -n auto

      - name: build docs
        run: mkdocs build
